name: android-master

on:
  push:
    branches: [master,fdroid]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'

      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            git@codeberg.org:CTemplar/android.git
          ssh_private_key:
            ${{ secrets.CODEBERG_SSH_PRIVATE_KEY }}

